CREATE TABLE "Reminder" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "donorId" TEXT NOT NULL,
  "eventId" TEXT,
  "remindOn" DATETIME NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'SCHEDULED',
  "channel" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Reminder_donorId_fkey" FOREIGN KEY ("donorId") REFERENCES "Donor"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Reminder_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TRIGGER "Reminder_updatedAt"
AFTER UPDATE ON "Reminder"
FOR EACH ROW
BEGIN
  UPDATE "Reminder" SET "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = OLD."id";
END;
